In [17]:
import pandas as pd

df = pd.read_csv('battery_health_dataset.csv')

df.head()

,Battery Age,Daily Usage Hours,Gaming User,Design Capacity,Cycle Count,CPU Usage,GPU Usage,Power Consumption,Average Temperature,Full Charge Capacity,Battery Health
0,5,9.797617,0,57884,1267,64.587764,43.887115,84.366245,35.645636,44961.935220,76.923383
1,9,7.101557,0,63824,1500,45.542182,36.534144,80.629042,31.782432,46619.665590,73.496153
2,9,10.085255,0,79414,1500,64.640516,52.238349,87.853504,32.122879,63343.419989,81.514041
3,5,7.946047,0,61142,1153,55.095724,30.535647,69.686012,30.371133,50407.438833,79.742100
4,7,9.628460,0,50956,1500,60.145756,36.749489,64.734123,27.536232,34757.377982,67.882552

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Battery Age           1200 non-null   int64
 1   Daily Usage Hours     1200 non-null   float64
 2   Gaming User           1200 non-null   int64
 3   Design Capacity       1200 non-null   int64
 4   Cycle Count           1200 non-null   int64
 5   CPU Usage             1200 non-null   float64
 6   GPU Usage             1200 non-null   float64
 7   Power Consumption     1200 non-null   float64
 8   Average Temperature   1200 non-null   float64
 9   Full Charge Capacity  1200 non-null   float64
 10  Battery Health        1200 non-null   float64
dtypes: float64(7), int64(4)
memory usage: 103.3 KB

In [19]:
df.shape

# с англ. - форма; форма матрица. 1200 - строк, 11 столбцов

(1200, 11)

In [20]:
import pandas as pd

sales = pd.Series(data=[10, 20, 30, 40],
               index = ['Asia', 
               'Europe',
               'America',
               'Africa'])

print(sales)

# одномерный массив данных

Asia       10
Europe     20
America    30
Africa     40
dtype: int64

In [21]:
import pandas as pd

sales = pd.DataFrame(index = ['USA', 'Russia', 'China'], 
                    data = {
                        'gdp': [28781, 2056, 18532],
                        'population': [335.8, 146.1, 1409.6],
                        'region': ['America', 'Europe', 'Asia']
                    })

print(sales)

          gdp  population   region
USA     28781       335.8  America
Russia   2056       146.1   Europe
China   18532      1409.6     Asia

In [22]:
df.describe()

,Battery Age,Daily Usage Hours,Gaming User,Design Capacity,Cycle Count,CPU Usage,GPU Usage,Power Consumption,Average Temperature,Full Charge Capacity,Battery Health
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,4.571667,6.435078,0.102500,62049.919167,993.813333,50.047021,37.081954,68.510005,30.483731,51798.125944,82.944518
std,2.831939,3.149664,0.303431,10096.807179,527.254899,18.859965,17.485642,21.213489,2.624044,11598.140456,9.924455
min,0.000000,1.002497,0.000000,45002.000000,0.000000,9.151884,5.000000,20.133013,22.908857,28181.020459,59.840266
25%,2.000000,3.722104,0.000000,53583.250000,530.500000,34.223028,24.084790,52.238214,28.758142,42865.372454,75.315849
50%,5.000000,6.322145,0.000000,61888.000000,1188.000000,50.097711,34.979134,67.399336,30.398357,51698.379658,81.461246
75%,7.000000,9.162563,0.000000,70734.750000,1500.000000,64.294947,46.615097,82.529511,32.231464,60403.354634,91.414773
max,9.000000,11.986722,1.000000,79959.000000,1500.000000,100.000000,98.339932,137.154936,39.934239,79263.000000,100.000000

In [23]:
df.max()

Battery Age                 9.000000
Daily Usage Hours          11.986722
Gaming User                 1.000000
Design Capacity         79959.000000
Cycle Count              1500.000000
CPU Usage                 100.000000
GPU Usage                  98.339932
Power Consumption         137.154936
Average Temperature        39.934239
Full Charge Capacity    79263.000000
Battery Health            100.000000
dtype: float64

<!-- Метод .loc в библиотеке Pandas служит для выбора строк и столбцов по их названиям (меткам), а не по порядковым номерам -->